routes/web.php
<?php

use App\Models\Car;
use Inertia\Inertia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Application;
use App\Http\Controllers\CarController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\ManagerCarController;
use App\Http\Controllers\PayPalController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Auth/Login');
});

/**
 *
 * A group of routers responsible for the user side
 *
 */
Route::middleware(["auth:sanctum", "user.check", "disabled.check"])->group(function () {
    Route::get('/', [CarController::class, "index"])->name('dashboard');
    Route::get('car/search', [CarController::class, "search"])->name('searchCar');
    Route::get('order/search', [OrderController::class, "search"])->name('searchOrder');
    Route::get('/success', [PayPalController::class, 'success']);
    Route::get('/error', [PayPalController::class, 'error']);

    Route::prefix('orders')->group(
        function () {
            Route::get('/{user}', [OrderController::class, "index"])->name('order');
            Route::get('/additionally/{order}', [OrderController::class, "ordersAdditionallyInfo"])->name('orderAdditionally');

            Route::post('/pay', [PayPalController::class, 'pay'])->name('pay');

            Route::post('/add/{user}', [OrderController::class, "addNew"])->name('addOrder');

            Route::get('/invoicepdf/{order}', [OrderController::class, 'invoicePdf'])
                ->name('orderInvoicePDF');

            Route::get('/delete/{order}', [OrderController::class, "delete"])->name('orderDelete');
        }
    );

    Route::prefix('profile')->group(
        function () {
            Route::get('/{user}', [UserController::class, 'profile'])->name('profile');
            Route::put('/update/{user}', [UserController::class, 'update'])->name('profile.update');
        }
    );
});

/**
 *
 * A group of routers responsible for the manager side
 *
 */
Route::middleware(['auth:sanctum', 'admin.check', "disabled.check"])->group(function () {
    Route::prefix('manager')->group(
        function () {
            Route::get('/', [ManagerController::class, 'index'])->name('manager');

            Route::get('/car/search', [ManagerController::class, 'searchCar'])->name('carSearch');
            Route::get('/order/search', [ManagerController::class, 'searchOrder'])->name('orderSearch');
            Route::get('/user/search', [ManagerController::class, 'searchUser'])->name('userSearch');

            Route::post('/car/update/status/indataorder', [ManagerController::class, 'updateCarStatusInOrderData'])
                ->name('carUpdateStatusInOrderData');

            Route::get('/sorting', [ManagerController::class, 'sorting'])->name('carSorting');

            Route::get('/users', [ManagerController::class, 'displayAllUsers'])->name('manager.users');
            Route::post('/users/edit', [ManagerController::class, 'editStatusUser'])
                ->name('editStatusUser');

            Route::get('/orders', [ManagerController::class, 'displayAllOrders'])->name('manager.orders');
            Route::post('/orders/edit', [ManagerController::class, 'editStatusOrder'])
                ->name('manager.editOrder');

            Route::get('/report', [ManagerController::class, 'report'])->name('report');
            Route::get('/report/data', [ManagerController::class, 'reportData'])->name('reportData');
            Route::get('/report/additiondata', [ManagerController::class, 'reportAdditionData'])
                ->name('manager.reportAddition');
            Route::post('/report/export', [ManagerController::class, 'reportExportExcel'])
                ->name('manager.reportExportExcel');

            Route::post('/car/editstatus', [ManagerController::class, 'editStatusCar'])
                ->name('manager.editCar');
            Route::resource('/car', ManagerCarController::class);
            Route::post('/car2/{car}', [ManagerCarController::class, 'update'])
                ->name('manager.reportExportExcel');

        }
    );
});

app/Http/Controllers/ManagerController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\Car;
use App\Models\User;
use Inertia\Inertia;
use App\Models\Order;
use App\Models\OrderData;
use App\Services\CarService;
use Illuminate\Http\Request;
use App\Services\UserService;
use App\Enums\OrderStatusEnum;
use App\Services\OrderService;
use App\Mail\OrderStatusChange;
use App\Exceptions\FileNotFound;
use App\Services\OrderDataService;
use App\Exports\CarReportDataExport;
use Illuminate\Support\Facades\Mail;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\UserReportDataExport;
use App\Services\ImageCarsService;
use App\Exports\OrderReportDataExport;
use App\Exceptions\DateReportException;
use App\Http\Requests\ReportDateRequest;
use App\Http\Requests\TableSortingRequest;
use App\Http\Requests\CarUpdateStatusRequest;
use App\Http\Requests\UserUpdateStatusRequest;
use App\Http\Requests\OrderUpdateStatusRequest;
use App\Http\Requests\AdditionDataReportRequest;
use App\Http\Requests\CarUpdateStatusInOrderDataRequest;

class ManagerController extends Controller
{
    /**
     * The class properties
     *
     * @var \App\Services\UserService
     * @var \App\Services\CarService
     * @var \App\Services\OrderService
     * @var \App\Services\OrderDataService
     * @var \App\Services\ImageCarsService
     */
    public UserService $user;
    public CarService $car;
    public OrderService $order;
    public OrderDataService $orderData;
    public ImageCarsService $imageCars;

    /**
     * @param \App\Services\UserService $user
     * @param \App\Services\CarService $car
     * @param \App\Services\OrderService $order
     * @param \App\Services\ImageCarsService $imageCars
     */
    public function __construct
    (
        UserService $user,
        CarService $car,
        OrderService $order,
        OrderDataService $orderData,
        ImageCarsService $imageCars
    ) {
        $this->user = $user;
        $this->car = $car;
        $this->order = $order;
        $this->orderData = $orderData;
        $this->imageCars = $imageCars;
    }

    /**
     * Method for displaying home manager page
     *
     * @return \Inertia\Inertia
     */
    public function index()
    {
        return Inertia::render('Manager/Index',
            [
                'usersCount' => $this->user->activeUsersCount(),
                'carsCount' => $this->car->count(),
                'ordersCount' => $this->order->count(),
            ]
        );
    }

    /**
     * Method for sorting cars
     *
     * @param \App\Http\Requests\TableSortingRequest $request
     * @return \Illuminate\Contracts\View\View
     */
    public function sorting(TableSortingRequest $request)
    {
        $requestData = $request->query();

        if ($requestData['table'] === 'users') {
            return Inertia::render('Manager/Users',
                [
                    'users' => $this->user->orderByUsersByOrdersData($requestData['column'], $requestData['keyword'])->withQueryString(),
                ]
            );
        }

        if ($requestData['table'] === 'cars') {
            return Inertia::render('CRUDCars/Index',
                [
                    'cars' => $this->car->orderByCarsData($requestData['column'], $requestData['keyword'])->withQueryString(),
                    'images' => $this->imageCars->all()
                ]
            );
        }

        if ($requestData['table'] === 'orders') {
            return Inertia::render('Manager/Orders',
                [
                    'orders' => $this->order->orderByOrdersByOrderData($requestData['column'], $requestData['keyword'])->withQueryString(),
                    'statuses' => OrderStatusEnum::values(),
                ]
            );
        }
    }

    /**
     * Method for finding cars
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Inertia\Inertia
     *
     */
    public function searchCar(Request $request)
    {
        if ($request->query('query') === null) {
            return Inertia::render('CRUDCars/Index',
                [
                    'cars' => $this->order->getAllWithPagination()->withQueryString(),
                ]
            );
        }

        return Inertia::render('CRUDCars/Index',
            [
                'cars' => Car::search($request->query('query'))->paginate(9),
            ]
        );
    }

    /**
     * Method for finding users
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Inertia\Inertia
     *
     */
    public function searchUser(Request $request)
    {
        if ($request->query('query') === null) {
            return Inertia::render('Manager/Users',
                [
                    'users' => $this->order->getAllWithPagination()->withQueryString(),
                ]
            );
        }

        return Inertia::render('Manager/Users',
            [
                'users' => User::search($request->query('query'))->paginate(9),
            ]
        );
    }

    /**
     * Method for finding orders
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Inertia\Inertia
     *
     */
    public function searchOrder(Request $request)
    {
        if ($request->query('query') === null) {
            return Inertia::render('Manager/Orders',
                [
                    'orders' => $this->order->getAllWithPagination(),
                    'statuses' => OrderStatusEnum::values(),
                ]
            );
        }

        return Inertia::render('Manager/Orders',
            [
                'orders' => Order::search($request->query('query'))->paginate(9),
                'statuses' => OrderStatusEnum::values(),
            ]
        );
    }

    /**
     * Method for displaying all users table
     *
     * @return \Inertia\Inertia
     */
    public function displayAllUsers()
    {
        return Inertia::render('Manager/Users',
            [
                "users" => $this->user->showUsers()
            ]
        );
    }

    /**
     * Method for edit status user
     *
     * @param \App\Http\Requests\UserUpdateStatusRequest $request
     * @return Illuminate\Http\Response
     */
    public function editStatusUser(UserUpdateStatusRequest $request)
    {
        $requestData = $request->validated();

        $user = $this->user->findById($requestData["id"]);

        $user->is_active = $requestData['status'];
        $user->save();

        return response()->json('Success');
    }

    /**
     * Method for displaying orders table
     *
     * @return \Inertia\Inertia
     */
    public function displayAllOrders()
    {
        return Inertia::render('Manager/Orders',
            [
                'orders' => $this->order->getAllWithPagination(),
                'statuses' => OrderStatusEnum::values(),
            ]
        );
    }

    /**
     * Method for edit status order
     *
     * @param \App\Http\Requests\OrderUpdateStatusRequest $request
     * @return Illuminate\Http\Response
     */

    public function editStatusOrder(OrderUpdateStatusRequest $request)
    {
        $requestData = $request->validated();

        $order = $this->order->findById($requestData["id"]);

        if ($requestData['status'] === 'cancel') {

            foreach ($order->subOrder()->get() as $subOrder) {
                $subOrder->is_active = 0;
                $subOrder->save();

                $subOrder->car()->first()->update(["is_active" => 1]);
            }

        }

        $order->status = $requestData['status'];
        $order->save();

        Mail::to($order->user()->first()->email)->send(new OrderStatusChange(
            $order,
            $order->user()->first()
        ));

        return response()->json('Success');
    }

    /**
     * Method for edit car status immediately on the page with the table
     *
     * @param \App\Http\Requests\CarUpdateStatusRequest $request
     * @return Illuminate\Http\Response
     */
    public function editStatusCar(CarUpdateStatusRequest $request)
    {
        $requestData = $request->validated();

        $car = $this->car->findById($requestData['id']);

        $car->is_active = $requestData['status'];
        $car->save();

        return response()->json('Success');
    }

    /**
     * Method for update car status in order data table
     *
     * @param \App\Http\Requests\CarUpdateStatusInOrderDataRequest $request
     * @return mixed
     */
    public function updateCarStatusInOrderData(CarUpdateStatusInOrderDataRequest $request)
    {
        $carInOrderData = OrderData::where('order_id', $request->all()['orderId'])->where('car_id', $request->all()['id'])->first();
        $carInOrderData->is_active = $request->all()['status'];
        $carInOrderData->save();
    }

    /**
     * Method for displaying report manager page
     *
     * @return \Inertia\Inertia
     */
    public function report()
    {
        return Inertia::render('Manager/Report');
    }

    /**
     * Method for displaying manager table with report data
     *
     * @param \App\Http\Requests\ReportDateRequest $request
     * @return \Inertia\Inertia
     */
    public function reportData(ReportDateRequest $request)
    {
        $date = explode(',', $request->validated()['date']);
        try {
            if (
                $date[0] < $date[1]
                && $date[0] <= Carbon::now()
                && $date[1] <= Carbon::now()
               ) {
                    return Inertia::render('Manager/Report',
                        [
                            'newUsers' => $this->user->countNewUsersDuringThePeriod(
                                $date[0],
                                $date[1]
                            ),
                            'newCars' => $this->car->countNewCarsDuringThePeriod(
                                $date[0],
                                $date[1]
                            ),

resources/views/manager/index.blade.php
@extends('adminlte::page')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <h1 class="m-0 d-flex justify-content-center">Home office page</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-6">

            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{$carsCount}}</h3>
                    <p>Cars</p>
                </div>
                <div class="icon">
                    <i class="fas fa-shopping-cart"></i>
                </div>
                <a href="{{route('car.index')}}" class="small-box-footer">
                    More info <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>



        <div class="col-lg-4 col-6">

            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>{{$usersCount}}</h3>
                    <p>Users</p>
                </div>
                <div class="icon">
                    <i class="fas fa-user-plus"></i>
                </div>
                <a href="{{ route('manager.users') }}" class="small-box-footer">
                    More info <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>

        <div class="col-lg-4 col-6">

            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>{{$ordersCount}}</h3>
                    <p>Orders</p>
                </div>
                <div class="icon">
                    <i class="fas fa-chart-pie"></i>
                </div>
                <a href="{{ route('manager.orders') }}" class="small-box-footer">
                    More info <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>

    </div>

@stop

resources/views/manager/orders.blade.php
@extends('adminlte::page')

@section('content')
    <div id="alert_placeholder"></div>

    @include('manager.orders_table')
@stop

@section('js')
    <script>
        $(function () {
            $('#orders').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });


        if (document.addEventListener) {
            document.addEventListener("change", function (event) {
                const data = {
                    status: event.target.value,
                    id: event.target.id,
                }
                statusOrderChange(data)
            });

            function statusOrderChange(data) {
                $("#" + data.id).html();
                $.ajax({
                    method: "POST",
                    url: "{{route('manager.editOrder')}}",
                    data: {"_token": "{{ csrf_token() }}", data}
                }).done(function (msg) {

                    showalert("Status was update")

                });
            }
        }

        function showalert(message) {

            $('#alert_placeholder').append(
                '<div id="alter-success" class="alert alert-success alert-dismissible fade show mt-2" role="alert">'
                +message+
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                '<span aria-hidden="true">&times;</span>' +
                '</button></div>'
            );
            window.scrollTo(0, 0);
        }
    </script>
@stop

resources/views/manager/orders_table.blade.php
<div class="row">
    <div class="col-12 mt-3">
        <div class="card">
            @include('partials.partials')
            <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12 col-md-6"></div>
                        <div class="col-sm-12 col-md-6"></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="orders" class="table table-bordered table-hover dataTable dtr-inline"
                                   aria-describedby="example2_info">
                                <thead>
                                <tr>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1"
                                        aria-label="Rendering engine: activate to sort column ascending"
                                    >User id
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1"
                                        aria-label="Rendering engine: activate to sort column ascending"
                                    >Car id
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-label="Browser: activate to sort column ascending"
                                    >Email
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-label="Platform(s): activate to sort column ascending"
                                    >Number of days
                                    </th>
                                    <th class="sorting sorting_desc" tabindex="0" aria-controls="example2"
                                        rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending"
                                        aria-sort="descending">Status
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-label="CSS grade: activate to sort column ascending"
                                    >Sum
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($orders as $order)
                                    <tr>
                                        <td class="dtr-control" tabindex="0">{{$order->user_id}}</td>

                                        <td class="dtr-control" tabindex="0">{{$order->car_id}}</td>

                                        <td>{{$order->user()->first()->email}}</td>

                                        <td class="sorting_1">{{$order->number_of_days}}</td>

                                        <td>
                                            <div class="report-change-order-status">

                                            <select name="status" id="status_{{$order->id}}" class="form-control w-100">
                                                @foreach(App\Enums\OrderStatusEnum::values() as $key=>$value)
                                                    <option @if($order->status->value == $value)
                                                                selected
                                                            @endif
                                                            value="{{ $value }}">{{ $key }}
                                                    </option>
                                                @endforeach
                                            </select>
                                            </div>
                                        </td>

                                        <td>{{$order->sum}}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">User id</th>
                                    <th rowspan="1" colspan="1">Car id</th>
                                    <th rowspan="1" colspan="1">Email</th>
                                    <th rowspan="1" colspan="1">Number of days</th>
                                    <th rowspan="1" colspan="1">Status</th>
                                    <th rowspan="1" colspan="1">Sum</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
<script>
    $(function () {
        $('#orders').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });

    $(".report-change-order-status").on('change', function (event) {
        const data = {
            status: event.target.value,
            id: event.target.id,
        }
        statusOrderChange(data)
    });

    function statusOrderChange(data) {
        $("#" + data.id).html();
        $.ajax({
            method: "POST",
            url: "{{route('manager.editOrder')}}",
            data: {"_token": "{{ csrf_token() }}", data}
        }).done(function (msg) {

            showalert("Status was update");

        });

    }

    function showalert(message) {

        $('#alert_placeholder').append(
            '<div id="alter-success" class="alert alert-success alert-dismissible fade show mt-2" role="alert">'
            + message +
            '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
            '<span aria-hidden="true">&times;</span>' +
            '</button></div>'
        );
        window.scrollTo(0, 0);
    }
</script>

resources/views/manager/profile.blade.php
@extends('adminlte::page')

@section('content')
    <div class="d-flex justify-content-center">
        <div class="card mb-3" style="width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="" class="img-fluid rounded-start" alt="Your Photo">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{$user->name}}</h5>
                        <p class="card-text">{{$user->email}}</p>
                        <p class="card-text"><small class="text-muted">Date of
                                registration: {{$user->created_at}}</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/manager/users.blade.php
@extends('adminlte::page')

@section('content')
   <div id="alert_placeholder"></div>

    @include('manager.users_table')
@stop

@section('js')
    <script>
        $(function () {
            $('#users').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });

        if (document.addEventListener) {
            document.addEventListener("change", function (event) {
                const data = {
                    is_active: event.target.value,
                    id: event.target.id,
                }

                statusUserChange(data)
            });

            function statusUserChange(data) {
                $("#" + data.id).html();
                $.ajax({
                    method: "POST",
                    url: "{{route('manager.editUser')}}",
                    data: {"_token": "{{ csrf_token() }}", data}
                }).done( data => {
                    showalert("Status was update");
                });
            }
        }

        function showalert(message) {

            $('#alert_placeholder').append(
                '<div id="alter-success" class="alert alert-success alert-dismissible fade show mt-2" role="alert">'
                +message+
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                '<span aria-hidden="true">&times;</span>' +
                '</button></div>'
            );
            window.scrollTo(0, 0);
        }
    </script>
@stop