routes/web.php
<?php

use App\Models\Car;
use Inertia\Inertia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Application;
use App\Http\Controllers\CarController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\ManagerCarController;
use App\Http\Controllers\PayPalController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Auth/Login');
});

/**
 *
 * A group of routers responsible for the user side
 *
 */
Route::middleware(["auth:sanctum", "user.check", "disabled.check"])->group(function () {
    Route::get('/', [CarController::class, "index"])->name('dashboard');
    Route::get('car/search', [CarController::class, "search"])->name('searchCar');
    Route::get('order/search', [OrderController::class, "search"])->name('searchOrder');
    Route::get('/success', [PayPalController::class, 'success']);
    Route::get('/error', [PayPalController::class, 'error']);

    Route::prefix('orders')->group(
        function () {
            Route::get('/{user}', [OrderController::class, "index"])->name('order');
            Route::get('/additionally/{order}', [OrderController::class, "ordersAdditionallyInfo"])->name('orderAdditionally');

            Route::post('/pay', [PayPalController::class, 'pay'])->name('pay');

            Route::post('/add/{user}', [OrderController::class, "addNew"])->name('addOrder');

            Route::get('/invoicepdf/{order}', [OrderController::class, 'invoicePdf'])
                ->name('orderInvoicePDF');

            Route::get('/delete/{order}', [OrderController::class, "delete"])->name('orderDelete');
        }
    );

    Route::prefix('profile')->group(
        function () {
            Route::get('/{user}', [UserController::class, 'profile'])->name('profile');
            Route::put('/update/{user}', [UserController::class, 'update'])->name('profile.update');
        }
    );
});

/**
 *
 * A group of routers responsible for the manager side
 *
 */
Route::middleware(['auth:sanctum', 'admin.check', "disabled.check"])->group(function () {
    Route::prefix('manager')->group(
        function () {
            Route::get('/', [ManagerController::class, 'index'])->name('manager');

            Route::get('/car/search', [ManagerController::class, 'searchCar'])->name('carSearch');
            Route::get('/order/search', [ManagerController::class, 'searchOrder'])->name('orderSearch');
            Route::get('/user/search', [ManagerController::class, 'searchUser'])->name('userSearch');

            Route::post('/car/update/status/indataorder', [ManagerController::class, 'updateCarStatusInOrderData'])
                ->name('carUpdateStatusInOrderData');

            Route::get('/sorting', [ManagerController::class, 'sorting'])->name('carSorting');

            Route::get('/users', [ManagerController::class, 'displayAllUsers'])->name('manager.users');
            Route::post('/users/edit', [ManagerController::class, 'editStatusUser'])
                ->name('editStatusUser');

            Route::get('/orders', [ManagerController::class, 'displayAllOrders'])->name('manager.orders');
            Route::post('/orders/edit', [ManagerController::class, 'editStatusOrder'])
                ->name('manager.editOrder');

            Route::get('/report', [ManagerController::class, 'report'])->name('report');
            Route::get('/report/data', [ManagerController::class, 'reportData'])->name('reportData');
            Route::get('/report/additiondata', [ManagerController::class, 'reportAdditionData'])
                ->name('manager.reportAddition');
            Route::post('/report/export', [ManagerController::class, 'reportExportExcel'])
                ->name('manager.reportExportExcel');

            Route::post('/car/editstatus', [ManagerController::class, 'editStatusCar'])
                ->name('manager.editCar');
            Route::resource('/car', ManagerCarController::class);
            Route::post('/car2/{car}', [ManagerCarController::class, 'update'])
                ->name('manager.reportExportExcel');

        }
    );
});

app/Http/Controllers/ManagerCarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Car;
use Inertia\Inertia;
use App\Services\CarService;
use App\Services\ImageCarsService;
use App\Http\Requests\CarUpdateRequest;
use App\Http\Requests\CreateNewCarRequest;
use Carbon\Carbon;

class ManagerCarController extends Controller
{
    /**
     * The class properties
     *
     * @var \App\Services\CarService
     * @var \App\Services\ImageCarsService
     */
    public CarService $car;
    public ImageCarsService $imageCars;

    /**
     * @param \App\Services\CarService $car
     * @param \App\Services\ImageCarsService $imageCars
     */
    public function __construct(CarService $car, ImageCarsService $imageCars)
    {
        $this->car = $car;
        $this->imageCars = $imageCars;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Inertia\Inertia
     */
    public function index()
    {
        return Inertia::render('CRUDCars/Index',
            [
                'cars' => $this->car->getAllWithPagination(),
                'images' => $this->imageCars->all()
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Inertia\Inertia
     */
    public function create()
    {
        return Inertia::render('CRUDCars/Create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\CreateNewCarRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateNewCarRequest $request)
    {
        $car = $this->car->create($request->except('image', 'is_active'));

        $car->is_active = $request->is_active;
        $car->save();

        if ($request->image) {

            foreach ($request->file('image') as $key => $image) {
                $carImage = $car->brand . '_' . $car->model . "_" . hash('sha256', Carbon::now()) . '.' . $image->getClientOriginalExtension();
                $image->storeAs('public/images/' . $car->id, $carImage);

                $this->imageCars->create([
                    'car_id' => $car->id,
                    'image' => $carImage,
                    'default' => ($key === 0) ? 1 : 0
                ]);
            }

        }

        return redirect()->route('car.create')->with(['updateSuccess' => 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Car $car
     *
     * @return \Inertia\Inertia
     */
    public function show(Car $car)
    {
        return Inertia::render('CRUDCars/Show', compact('car'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Car $car
     *
     * @return \Inertia\Inertia
     */
    public function edit(Car $car)
    {
        return Inertia::render('CRUDCars/Edit', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\CarUpdateRequest $request
     * @param \App\Models\Car $car
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CarUpdateRequest $request, Car $car)
    {
        $car->update($request->except(['_method', '_token', 'image', 'is_active']));

        $car->is_active = $request->is_active;
        $car->save();

        $arrayImagesCar = $this->imageCars->getCarImages($car->id)->toArray();

        foreach ($request->image as $value) {
            foreach ($arrayImagesCar as $image) {
                if (gettype($value) === 'array' && $value['name'] === $image['image']) {
                    $index = array_search($image, $arrayImagesCar);
                    unset($arrayImagesCar[$index]);
                }
            }
        }

        $this->imageCars->deleteCarImages($car->id, $arrayImagesCar);

        foreach($arrayImagesCar as $image) {
            array_map('unlink', glob(storage_path('app/public/images/' . $car->id . '/' . $image['image'])));
        }

        array_filter($request->image, function($image) use ($car){
            if (gettype($image) === 'object') {
                $carImage = $car->brand . '_' . $car->model . "_"
                . hash('sha256', $image->getClientOriginalName())
                . '.' . $image->getClientOriginalExtension();

                $image->storeAs('public/images/' . $car->id, $carImage);

                $this->imageCars->create(
                    [
                        'car_id' => $car->id,
                        'image' => $carImage,
                        // 'default' => ($key === 0) ? 1 : 0,
                        'size' => $image->getSize(),
                    ]
                );
            }
        });

        return redirect()->route('car.index')->with(['updateSuccess' => "success"]);
    }
}

resources/views/manager_car/cars_table.blade.php
<div class="row">
    <div class="col-12 mt-3">
        <div class="card">
            @include('partials.partials')
            <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12 col-md-6"></div>
                        <div class="col-sm-12 col-md-6"></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="cars" class="table table-bordered table-hover dataTable dtr-inline"
                                   aria-describedby="example2_info">
                                <thead>
                                <tr>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1"
                                        aria-label="Rendering engine: activate to sort column ascending"
                                        style="width: 10%">Id
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-label="Browser: activate to sort column ascending"
                                        style="width: 20%">Brand and Models
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-label="Platform(s): activate to sort column ascending"
                                        style="width: 10%">
                                        Status
                                    </th>
                                    <th class="sorting sorting_desc" tabindex="0" aria-controls="example2"
                                        rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending"
                                        aria-sort="descending" style="width: 15%">Price per day
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-label="CSS grade: activate to sort column ascending"
                                        style="width: 20%">Actions
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($cars as $car)
                                    <tr>
                                        <td class="dtr-control" tabindex="0">{{$car->id}}</td>
                                        <td>{{$car->brand . ' ' .$car->model}}</td>
                                        <td>
                                            <div class="report-change-car-status">
                                                <select name="is_active" id="is_active_{{$car->id}}"
                                                        class="form-control w-100">

                                                    <option @if($car->is_active) selected
                                                            @endif value="1">Active
                                                    </option>

                                                    <option @if(!$car->is_active) selected
                                                            @endif value="0">Locked
                                                    </option>

                                                </select>
                                            </div>
                                        </td>
                                        <td class="sorting_1">$@convert($car->price_per_day)</td>
                                        <td>
                                            <div>
                                                <a class="btn btn-primary btn-sm" href="{{route('car.show', ["car" => $car->id])}}">
                                                    <i class="fas fa-folder">
                                                    </i>
                                                    View
                                                </a>
                                                <a class="btn btn-info btn-sm" href="{{route('car.edit', ["car" => $car->id])}}">
                                                    <i class="fas fa-pencil-alt">
                                                    </i>
                                                    Edit Car
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">Id</th>
                                    <th rowspan="1" colspan="1">Name</th>
                                    <th rowspan="1" colspan="1">Status</th>
                                    <th rowspan="1" colspan="1">Price per day</th>
                                    <th rowspan="1" colspan="1">Actions</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

<script>
    $(function () {
        $('#cars').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });

    $(".report-change-car-status").on('change', function (event) {
        const data =
            {
                is_active: event.target.value,
                id: event.target.id,
            }
        statusCarChange(data)
    });

    function statusCarChange(data) {
        $("#" + data.id).html();
        $.ajax({
            method: "POST",
            url: "{{route('manager.editCar')}}",
            data: {"_token": "{{ csrf_token() }}", data}
        }).done(function (msg) {

            showalert("Status was update");

        });
    }

    function showalert(message) {

        $('#alert_placeholder').append(
            '<div id="alter-success" class="alert alert-success alert-dismissible fade show mt-2" role="alert">'
            + message +
            '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
            '<span aria-hidden="true">&times;</span>' +
            '</button></div>'
        );
        window.scrollTo(0, 0);
    }
</script>

resources/views/manager_car/create.blade.php
@extends('adminlte::page')

@section('content')
    <form enctype="multipart/form-data" method="POST" action="{{ route('car.store') }}">
        @csrf
        <div class="row">
            @include('partials.partials')
            <div class="col-md-12 mt-3">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create car</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="brand">Brand</label>
                                    <input type="text" id="brand" name="brand"
                                           class="form-control @error('brand') is-invalid @enderror"
                                           value="{{old('brand') ?? '' }}">
                                    @error('brand')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="model">Model</label>
                                    <input id="model" name="model"
                                           class="form-control @error('model') is-invalid @enderror"
                                           value="{{old('model') ?? '' }}">
                                    @error('model')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="type">Type</label>
                                    <input id="type" name="type"
                                           class="form-control @error('type') is-invalid @enderror"
                                           value="{{old('type') ?? '' }}">
                                    @error('type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="box_type">Box type</label>
                                    <input id="box_type" name="box_type"
                                           class="form-control @error('box_type') is-invalid @enderror"
                                           value="{{old('box_type') ?? '' }}">
                                    @error('box_type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="fuel_type">Fuel type</label>
                                    <input id="fuel_type" name="fuel_type"
                                           class="form-control @error('fuel_type') is-invalid @enderror"
                                           value="{{old('fuel_type') ?? '' }}">
                                    @error('fuel_type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="seating">Seating</label>
                            <input id="seating" name="seating" class="form-control
                            @error('seating') is-invalid @enderror"
                                   value="{{old('seating') ?? '' }}">
                            @error('seating')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="price_per_day">Price per day</label>
                            <input id="price_per_day" name="price_per_day" class="form-control
                            @error('price_per_day') is-invalid @enderror"
                                   value="{{old('price_per_day') ?? '' }}">
                            @error('price_per_day')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="status">Status</label>
                            <select name="is_active" id="status"
                                    class="form-control custom-select @error('is_active') is-invalid @enderror">

                                <option @if(old('is_active') && old('is_active') == 1) selected
                                        @endif value="1">Active</option>

                                <option @if(old('is_active') && old('is_active') == 0) selected
                                        @endif value="0">Locked</option>

                            </select>
                            @error('is_active')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="image">File</label>
                            <input name="image" id="image" type="file"
                                   class="form-control @error('image') is-invalid @enderror" placeholder="">
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <input type="submit" value="Create" class="btn btn-success float-right">
            </div>
        </div>
    </form>
@stop

@section('js')
@stop

resources/views/manager_car/index.blade.php
@extends('adminlte::page')

@section('content')
    <div id="alert_placeholder"></div>

    @include('manager_car.cars_table')
@stop

@section('js')
    <script>
        $(function () {
            $('#cars').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });
    </script>

    <script>
        if (document.addEventListener) {
            document.addEventListener("change", function (event) {
                const data = {
                    is_active: event.target.value,
                    id: event.target.id,
                }
                statusCarChange(data)
            });

            function statusCarChange(data) {
                $("#" + data.id).html();
                $.ajax({
                    method: "POST",
                    url: "{{route('manager.editCar')}}",
                    data: {"_token": "{{ csrf_token() }}", data}
                }).done(function (msg) {

                    showalert("Status was update")

                });
            }
        }

        function showalert(message) {

            $('#alert_placeholder').append(
                '<div id="alter-success" class="alert alert-success alert-dismissible fade show mt-2" role="alert">'
                +message+
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                '<span aria-hidden="true">&times;</span>' +
                '</button></div>'
            );
            window.scrollTo(0, 0);
        }
    </script>
@stop

resources/views/manager_car/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        @include('partials.partials')
        <div class="col-md-12">
            <div class="card">
                <div class="card-body box-profile">
                    @if($car->img != null && file_exists(storage_path('/app/public/images/'.$car->img)))
                    <div class="text-center">
                        <img class="profile-user-img img-fluid" src="{{url('storage/images/'.$car->img)}}">
                    </div>
                    @else
                        <div class="text-center">
                            <img class="profile-user-img img-fluid" src="" alt="Car picture">
                        </div>
                    @endif
                    <h3 class="profile-username text-center">#{{ $car->id }} {{ $car->brand }}</h3>

                    <p class="text-muted text-center">{{ $car->model }}</p>

                    <ul class="list-group list-group-unbordered mb-3">
                        <li class="list-group-item">
                            <b>Type</b> <a class="float-right">{{$car->type}}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Box type</b> <a class="float-right">{{$car->box_type}}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Fuel type</b> <a class="float-right">{{$car->fuel_type}}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Seating</b> <a class="float-right">{{$car->seating}}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Price per days</b> <a class="float-right">$@convert($car->price_per_day)</a>
                        </li>
                        <li class="list-group-item">
                            <b>Creation Date</b> <a class="float-right">{{$car->created_at}}</a>
                        </li>
                    </ul>

                    <a href="{{route('car.edit', ["car" => $car->id])}}" class="btn btn-primary btn-block">
                        <b>Edit</b>
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
@stop